

name: Build client

on:
  release:
    types: [created]

jobs:
  test_and_build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun i
      - name: Run Trivy scanner on fs
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: 1
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'CRITICAL,HIGH'
      - name: Run build
        run: bun run build
        env:
          REF_NAME: ${{ github.ref_name }}
      - name: Set tag
        id: tag
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true"  ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.release.prerelease }}" == "false" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: ${{ steps.tag.outputs.tag }}